// Realistic payloads captured from the LIVE server during the audit.
module.exports = {
  "/api/state": {
    type:"full_state",
    config:{ watchlist:["ASTS","NBIS","HCA"], risk_level:"TURBO",
      trading:{auto_trade:false,mode:"HYBRID",watch_execute:"WATCH",live_execution_enabled:false,max_positions:25,scan_interval_minutes:5},
      risk:{kill_switch_triggered:false,CONSERVATIVE:{buy_score_threshold_pct:68,stop_loss_swing_pct:4,vix_entry_max:22},MODERATE:{},AGGRESSIVE:{},TURBO:{}},
      screener:{enabled:true,max_candidates:30},
      rotation:{enabled:true,min_candidate_score:80,max_victim_health_score:55,min_hold_days:3,max_rotations_per_week:2},
      account:{auto_sync:true, robinhood_account_number:"",
               _account_number_source:{env_var:"RH_ACCOUNT_NUMBER",is_set:true,masked:"••••1234"}} },
    regime:{dominant_regime:"BULL",bull_pct:46,bear_pct:17,choppy_pct:38,updated_at:"2026-07-26T17:30:00"},
    market_context:{fg_score:39,fg_rating:"fear",vix:18.6,hours_to_next_macro:999.0,blackout_active:false,as_of:"2026-07-26T17:30:00"},
    positions:[], recent_signals:[
      {ticker:"TSLA",signal:"HOLD",timestamp:"2026-07-26T17:33:00",trade_mode:"HYBRID",data_quality:"lite",
       rules_failed:[{name:"STALE_QUOTE",detail:"Quote 2733 min old (max 30)"}]},
      {ticker:"NKE",signal:"HOLD",timestamp:"2026-07-26T17:33:00",trade_mode:"HYBRID",data_quality:"lite",
       rules_failed:[{name:"STALE_QUOTE",detail:"Quote 2733 min old (max 30)"}]}
    ],
    daily_stats:{cycles_run:1,signals_generated:42,trades_placed:0,realized_pnl:0},
    paper_realized_today:0, health_score:null, portfolio_heat:{current_heat_pct:0,max_heat_pct:7}
  },
  "/api/status": { market_open:false, next_open_et:"2026-07-27T09:00:00-04:00",
    last_cycle:{cycle_num:7,timestamp:"2026-07-26T17:33:00",ticker_count:42,duration:190,triggered_by:"manual",blocked:false},
    kill_switch:false, scan_interval_minutes:5, is_running:false, manual_cycle_running:false,
    next_run_at:"2026-07-27T09:00:00-04:00", kill_reason:null, pid:64901,
    execution_posture:{mode:"PAPER",colour:"green",master_switch:false,watch_execute:"WATCH",auto_trade:false,
      risk_level:"TURBO",kill_switch:false,force_paper:true,validation:"no validation receipt - run the backtest gate first"} },
  "/api/robinhood/status": { configured:false, watch_execute:"WATCH", auto_trade:false, read_ok:null,
    orders_breaker_open:false, live_execution_enabled:false, live_trading_armed:false,
    execution_path:"claude_desktop", read_error:"ROBINHOOD_USERNAME/ROBINHOOD_PASSWORD are not set in .env." },
  "/api/signals?limit=100": [
      {ticker:"TSLA",signal:"HOLD",timestamp:"2026-07-26T17:33:00",trade_mode:"HYBRID",data_quality:"lite",
       rules_failed:[{name:"STALE_QUOTE",detail:"Quote 2733 min old (max 30)"}]},
      {ticker:"AAPL",signal:"BUY",timestamp:"2026-07-26T17:33:00",trade_mode:"SWING",data_quality:"complete",
       buy_pct:72,price:210.5,bucket_scores:[{name:"TREND",qualified:true,pct_of_own_max:0.8}]},
      {ticker:"MSFT",signal:"HOLD",timestamp:"2026-07-26T17:33:00",trade_mode:"SWING",
       rules_failed:[{name:"ALREADY_OPEN",detail:"position already open"}]}
  ],
  "/api/ticker/names": {ASTS:"AST SpaceMobile",TSLA:"Tesla, Inc."},
  "/api/ticker/health": [],
  "/api/analytics/performance": {n_closed_patterns:3, profit_factor:null, sharpe_ratio:null},
  "/api/analytics/regime_performance": {},
  "/api/learning/runs": [],
  "/api/backtest/status": {running:false}, "/api/backtest/latest": null, "/api/backtest/runs": [],
  "/api/trades": [], "/api/positions": [], "/api/paper/summary": {seeded:false}, "/api/paper/trades": [],
  "/api/paper/equity_history": [], "/api/real/summary": {connected:true, credentials_configured:true, read_error:null,
    account_number:"\u2022\u2022\u2022\u20223794", account_source:"agentic_configured",
    account_value:2004.15, cash:1859.94, holdings_value:144.21, buying_power:1839.85,
    invested_cost:240.11, market_value:245.77, unrealized_pnl:5.66,
    realized_pnl_today:0, realized_pnl_all_time:-369.91,
    trades_placed_today:0, winning_trades_today:0, n_open:4,
    open_positions:[{ticker:"CLF",trade_mode:"DAY",entry_price:11.71,shares:8.54,cost:99.96,
                     current_price:11.93,market_value:101.88,unrealized_pnl:1.92,opened_at:"2026-07-24T16:38:00"}]},
  "/api/alerts": [],
  // Captured 2026-07-26: the local book carried CLF, bought in the PRIMARY
  // account, while the configured account holds only OII/SW/DLR.
  "/api/real/reconcile": {checked_at:"2026-07-26T18:00:00", account_number:"\u2022\u2022\u2022\u20223794",
    broker_read_ok:true, read_error:null,
    matched:[{ticker:"OII",local_shares:1.97,broker_shares:1.97,issue:null},
             {ticker:"SW",local_shares:0.4127,broker_shares:0.4127,issue:null},
             {ticker:"DLR",local_shares:0.1,broker_shares:0.1,issue:null}],
    local_only:[{ticker:"CLF",local_shares:8.54,broker_shares:0,issue:"not_held_in_this_account"}],
    broker_only:[]}, "/api/sources": {sources:[{name:"yfinance",kind:"MCP",role:"Quotes",optional:false,status:"OK",note:"Last success 2026-07-26",consecutive_failures:0}]},
  "/api/news": {news:[{ticker:"ASTS",headline:"AST SpaceMobile <b>upgraded</b>",sentiment_label:"bullish",last_seen_at:"2026-07-26T17:32:00"}],
    market_mood:{fear_greed_score:39,fear_greed_rating:"fear",vix_level:18.6,regime:"BULL",blackout_active:false,hours_to_next_macro:999.0,as_of:"2026-07-26T17:30:00"}},
  "/api/logs": {lines:[
      {raw:"2026-07-26 12:33:10,497 INFO [scheduler] __main__: Analyzing TSLA...",source:"scheduler"},
      {raw:"2026-07-26 12:33:11,472 ERROR [server] app: boom",source:"server"},
      {raw:"Traceback (most recent call last):",source:"server"},
      {raw:"  File \"/x/y.py\", line 4, in <module>",source:"server"},
      {raw:"RuntimeError: config.yaml references ${RH_ACCOUNT_NUMBER} but it is not set.",source:"server"}]},
  "/api/analytics/attribution": {}, "/api/analytics/regret": {trades:[]},
  "/api/analytics/threshold_regret": {not_yet_run:true,message:"no run yet"},
  "/api/analytics/threshold_regret/runs": [],
  "/api/strategy": null,
  "/api/prompt": {content:""}
};
